name: Build and Release EXE

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyautogui matplotlib scipy seaborn python-pptx pytube youtube-transcript-api pillow

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon="screenshots\\app_icon_256×256.ico" --name YouTubeTranscriptSummary YouTubeTranscriptSummary.py

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/YouTubeTranscriptSummary.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
