name: Build Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install youtube-transcript-api

      - name: Package Application with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --name "YouTubeTranscriptAnalyzer" --onefile your_script_name.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/YouTubeTranscriptAnalyzer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
